# Generated by Django 3.0.4 on 2020-04-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pelicula_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cartelera',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
