# Generated by Django 3.0.4 on 2020-04-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200425_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='peliculas',
            field=models.ManyToManyField(related_name='peliculas', to='app.Pelicula'),
        ),
    ]
