# Generated by Django 3.0.4 on 2020-04-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200426_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='actores',
            new_name='actor',
        ),
    ]
