# Generated by Django 3.0.4 on 2020-04-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200426_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='actor',
            new_name='actores',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='year',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='cartelera',
            new_name='enCartelera',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='descripcion',
            new_name='sinopsis',
        ),
    ]
