# Generated by Django 3.0.4 on 2020-04-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200426_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
