# Generated by Django 3.0.4 on 2020-04-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='app.Calificacion'),
        ),
        migrations.AddField(
            model_name='user',
            name='calificaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='app.Calificacion'),
        ),
    ]
