# Generated by Django 3.0.4 on 2020-04-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200427_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='calificaciones',
            new_name='calificacion',
        ),
    ]
