# Generated by Django 3.0.4 on 2020-04-27 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20200427_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='año',
            new_name='anio',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='app.Pelicula'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
