# Generated by Django 3.0.4 on 2020-04-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificacionesp', to='app.Pelicula'),
        ),
    ]
