# Generated by Django 3.0.4 on 2020-04-30 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20200429_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calip', to='app.Pelicula'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caliu', to=settings.AUTH_USER_MODEL),
        ),
    ]
