# Generated by Django 3.0.4 on 2020-04-30 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20200430_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='app.Pelicula'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
